Added information about EvalAI in Readme.
Cloud-CV/EvalAI-ngx pull request #11
Opened 2018-02-14 17:28 UTC by Arun-Jain

Fixes #10 @deshraj @aka-jain @RishabhJain2018 Please review this PR.

2018-02-14 21:14 UTC, RishabhJain2018 requested changes
@Arun-Jain can you please check why images aren't loading? Rest looks good to me!

2018-02-15 07:01 UTC, Arun-Jain commented
@RishabhJain2018 Everything is working fine on my side. Can you please review it again?
![screenshot from 2018-02-15 12-21-22](https://user-images.githubusercontent.com/16155501/36244238-5fd52f86-124b-11e8-9e27-2ef97b921165.png)

2018-02-17 19:09 UTC, deshraj requested changes
Remove the file `src/assets/images/vqa_leaderboard.png`

2018-02-17 19:09 UTC, deshraj commented on README.md
> +EvalAI and EvalAI-ngx is currently maintained by [Deshraj Yadav](https://deshraj.github.io), [Akash Jain](http://www.jainakash.in/), [Taranjeet Singh](http://taranjeet.github.io/), [Shiv Baran Singh]
Please change it to 
```
EvalAI-ngx is currently maintained by [Akash Jain](http://www.jainakash.in/), [Shiv Baran Singh](http://www.shivbaran.in/), [Rishabh Jain](https://rishabhjain2018.github.io/) and [Deshraj Yadav](https://deshraj.github.io).
```

2018-02-17 20:18 UTC, Arun-Jain commented
@deshraj Updated. Please review the changes.

2018-02-18 02:11 UTC, deshraj approved these changes

2018-02-18 02:12 UTC, merged