Added dynamic title for all components
Cloud-CV/EvalAI-ngx pull request #20
Opened 2018-02-25 16:51 UTC by aka-jain

@spyshiv please take a look.

2018-02-26 08:48 UTC, spyshiv requested changes
@aka-jain There are many lint erros. please fix that. Rest of thing LGTM.

2018-02-27 18:05 UTC, aka-jain commented
Fixed lint errors @spyshiv, have a look.

2018-02-27 19:30 UTC, spyshiv approved these changes

2018-02-27 19:31 UTC, spyshiv commented
LGTM. Merging this

2018-02-27 19:32 UTC, merged