Added target=_new attribute to appropriate links.
Cloud-CV/EvalAI-ngx pull request #216
Opened 2019-12-03 18:45 UTC by Mateusz1223

Fixes #

#### Changes proposed in this pull request:

-

- Link to live demo: http://pr-XXX-evalai.surge.sh 

-

2019-12-03 20:06 UTC, Sanji515 reviewed
Just a minor comment. Rest LGTM!

2019-12-03 20:06 UTC, Sanji515 commented on src/app/components/get-involved/get-involved.component.html
> +<app-footer></app-footer>
@Mateusz1223 Can you please add a new line here?

2019-12-03 20:07 UTC, Sanji515 commented
Also, @Mateusz1223 Please update the PR description.

2019-12-04 04:57 UTC, Ram81 requested changes

2019-12-04 04:57 UTC, Ram81 commented on src/app/components/about/about.component.html
> +					<a href="http://cloudcv.org" target="_new" class="blue-text">CloudCV</a>. CloudCV aims to make AI research
@Mateusz1223 please add `target="_blank"` instead of `target="new"`

2019-12-04 06:44 UTC, Ram81 approved these changes
LGTM 👍

2019-12-04 06:44 UTC, Sanji515 approved these changes

2019-12-04 06:55 UTC, RishabhJain2018 approved these changes

2019-12-04 06:57 UTC, merged