Ndu jay
Cloud-CV/EvalAI-ngx pull request #217
Opened 2019-12-04 14:35 UTC by nsjcorps

#### Changes proposed in this pull request:

-  Added subscribe form to Home Page

#### DEMO VIDEO
![bandicam-2019-12-04-12-45-41-252](https://user-images.githubusercontent.com/35180217/70151309-b3cd0d00-16ab-11ea-921b-338351f38c03.gif)

2019-12-04 18:20 UTC, Sanji515 commented
@nsjcorps Please fix the travis build

2019-12-04 20:22 UTC, nsjcorps commented
I have made the necessary changes to pass the lint. Sorry about that,

2019-12-05 04:29 UTC, Ram81 requested changes
@nsjcorps please change the PR name based on instructions

2019-12-05 07:45 UTC, nsjcorps commented
I have done that sir.

2019-12-06 13:01 UTC, vkartik97 commented
Hi @nsjcorps 
The button does work, but when I enter email id which was to already subscribed earlier, the error message `Something went wrong <400>` is popped up.
<img width="1918" alt="Screenshot 2019-12-06 at 6 25 02 PM" src="https://user-images.githubusercontent.com/3920286/70324792-7062d200-1856-11ea-8fda-4578203d0331.png">

It would be better to display the message that clearly give the information to the user that the email is already subscribed and not a generic error. Something like, `You have already subscribed to EvalAI`

2019-12-06 13:36 UTC, nsjcorps commented
Alright I will fix it to work as it should

2019-12-06 14:43 UTC, vkartik97 commented
@nsjcorps 
I am getting following message when trying to subscribe with same email id:
<img width="1680" alt="Screenshot 2019-12-06 at 8 09 07 PM" src="https://user-images.githubusercontent.com/3920286/70331065-bc1c7800-1864-11ea-98da-f82ad9ec6d29.png">

2019-12-06 15:51 UTC, nsjcorps commented
It should work well now. I was apparently checking the wrong property.

2019-12-07 05:22 UTC, Ram81 requested changes

2019-12-07 05:22 UTC, Ram81 commented on src/app/components/home/home.component.ts
> +  /**
realign this

2019-12-07 05:22 UTC, Ram81 commented on src/app/components/home/home.component.ts
> +   * @param self  context value of this
remove extra space

2019-12-07 05:22 UTC, Ram81 commented on src/app/components/home/home.component.ts
> +          setTimeout(() => self.globalService.showToast('success', err.error.message, 5), 1000);
@nsjcorps why are we showing a `success` message when there is a error?

2019-12-07 05:22 UTC, Ram81 commented on src/app/services/endpoints.service.ts
> +  /**
Add a new line above this

2019-12-07 05:22 UTC, Ram81 commented on src/app/services/endpoints.service.ts
> +
Remove new line

2019-12-07 11:08 UTC, nsjcorps commented
I have made the requested changes

2019-12-07 16:34 UTC, Ram81 requested changes
@nsjcorps some minor changes

2019-12-07 16:34 UTC, Ram81 commented on src/app/components/home/home.component.ts
> +
remove extra newline

2019-12-07 16:34 UTC, Ram81 commented on src/app/components/home/home.component.ts
> +export class HomeComponent implements OnInit, AfterViewInit, OnDestroy {
Add a newline above this

2019-12-08 05:30 UTC, RishabhJain2018 approved these changes
LGTM :) Thanks @nsjcorps for adding it.
Thanks @Ram81 @vkartik97 @Sanji515 for the reviews.

2019-12-08 05:30 UTC, merged

2019-12-08 07:02 UTC, nsjcorps commented
Thank you @RishabhJain2018 for merging the pull request and thank you @Sanji515 @vkartik97 @Ram81 for all the reviews.