Fix base components loading
Cloud-CV/EvalAI-ngx pull request #239
Opened 2019-12-13 20:30 UTC by rlee7

Moves the loading of the header and footer components from every parent component to just the main app component.

- Link to live demo: http://pr-XXX-evalai.surge.sh

2019-12-14 05:44 UTC, Ram81 requested changes

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/challenge/challenge.component.html
> +
@rlee7 Can you remove the blankline

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/contact/contact.component.html
> +
Same here

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/dashboard/dashboard.component.html
> +
Same here

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/get-involved/get-involved.component.html
> +
Same here

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/home/home.component.html
> +
Same here

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/home/home.component.html
> +
Same here

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/publiclists/publiclists.component.html
> +
Same here

2019-12-14 05:44 UTC, Ram81 commented on src/app/components/profile/profile.component.html
> +
Same here

2019-12-15 05:50 UTC, Ram81 approved these changes
@rlee7 LGTM 👍 . @Sanji515 @lunayach can you guys review once.

2019-12-15 06:16 UTC, Sanji515 commented
![Screenshot from 2019-12-15 11-33-59](https://user-images.githubusercontent.com/32524438/70858886-82b4ce00-1f30-11ea-916c-cf4afb654a34.png)


@rlee7 Can you please fix this (^)

2019-12-15 10:47 UTC, rlee7 commented
@Sanji515 What page is that? I can't seem to replicate on my machine

2019-12-15 10:50 UTC, Sanji515 commented
> @Sanji515 What page is that? I can't seem to replicate on my machine

You can see this on the any page where this sidebar displays. Like `Dashboard page`.

2019-12-15 11:00 UTC, lunayach commented
@rlee7 I'm also seeing the same issue.

2019-12-15 23:19 UTC, rlee7 commented
@Sanji515 I think it should be fixed now, please confirm for your machine

2019-12-16 10:25 UTC, pushkalkatara commented
1. The `All Challenges` and `Forum` tabs are displayed on the login page. Please fix this.
![bug](https://user-images.githubusercontent.com/21266230/70899170-1a431b00-201c-11ea-96f9-c1e84440d299.png)

2. Still, I think the dashboard issue is not fixed.
![bug 2](https://user-images.githubusercontent.com/21266230/70899310-655d2e00-201c-11ea-9586-c9daff6edfcb.png)

2019-12-19 04:12 UTC, closed without merging