Fixed typos in EvalAi-ngx
Cloud-CV/EvalAI-ngx pull request #256
Opened 2020-01-04 19:51 UTC by nsjcorps

I fixed a few lines where there were typos or wrong capitalization.

@Ram81 @pushkalkatara @RishabhJain2018 @yashdusing @Sanji515 @vkartik97 Please take a look

2020-01-06 21:51 UTC, krtkvrm approved these changes

2020-01-07 05:11 UTC, pushkalkatara commented
@nsjcorps Please update the branch with the base branch.

2020-01-07 08:58 UTC, nsjcorps commented
@pushkalkatara Done!!

2020-01-07 14:57 UTC, RishabhJain2018 requested changes

2020-01-07 14:57 UTC, RishabhJain2018 commented on src/app/components/get-involved/get-involved.component.html
> +      team of volunteers around the world who want to reduce the barrier of
Please revert this change.

2020-01-07 15:00 UTC, nsjcorps commented on src/app/components/get-involved/get-involved.component.html
> +      team of volunteers around the world who want to reduce the barrier of
Alright. Will do now @RishabhJain2018

2020-01-07 15:00 UTC, nsjcorps commented on src/app/components/get-involved/get-involved.component.html
> +      team of volunteers around the world who want to reduce the barrier of
I am also updating the branch

2020-01-07 15:01 UTC, nsjcorps commented on src/app/components/get-involved/get-involved.component.html
> +      team of volunteers around the world who want to reduce the barrier of
I am also updating the branch

2020-01-07 15:07 UTC, nsjcorps commented
Done!! @RishabhJain2018

2020-01-07 23:11 UTC, RishabhJain2018 approved these changes

2020-01-07 23:12 UTC, merged