Addresses #24: Common button styles for EvalAI
Cloud-CV/EvalAI-ngx pull request #27
Opened 2018-02-28 11:47 UTC by harshit98

Addresses #24:

- Common button styles for Eval AI as per the shared design.
- After merge of this PR, we can further iterate with the improvements in design.

Screenshot of the work:

![screen shot 2018-02-28 at 5 14 52 pm](https://user-images.githubusercontent.com/22245418/36786119-37840aba-1cab-11e8-91e2-d4d07f9875b4.png)

2018-02-28 16:52 UTC, aka-jain requested changes

2018-02-28 16:52 UTC, aka-jain commented on src/index.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
@harshit98 please don't use bootstrap. You have to write these component from scratch.

2018-02-28 16:52 UTC, aka-jain commented on src/app/home/home.component.scss
> +    box-shadow: none;
Add new line here.

2018-02-28 16:52 UTC, aka-jain commented on src/app/home/home.component.scss
> +.row {
Why you are modifying row class? Any specific reason? Also we already have grid and base file. Please import those to use row or col.

2018-02-28 18:55 UTC, harshit98 commented
@aka-jain I have written the code from scratch. Kindly review. Here is the new screenshot of the work: 

![screen shot 2018-03-01 at 12 22 19 am](https://user-images.githubusercontent.com/22245418/36806677-d50f9ba6-1ce6-11e8-8f37-07eadccea962.png)

I have not changed the font because already there is an issue opened regarding it. 👍

2018-03-01 06:21 UTC, aka-jain commented on src/app/home/home.component.scss
> +.clearfix {
@harshit98 can you please explain why you are using clearfix class for giving bg color?

2018-03-01 06:42 UTC, harshit98 commented on src/app/home/home.component.scss
> +.clearfix {
@aka-jain Due to the white background, I was unable to verify the buttons design because in `.btn` class I have kept `background: none;` to keep the button transparent. So, I thought to keep the background purple as per the shared design for the verification purpose. When background of the website will be implemented, `.clearfix` can be removed. : )

2018-03-10 16:45 UTC, closed without merging