Modal scroll fix
Cloud-CV/EvalAI-ngx pull request #273
Opened 2020-01-15 08:11 UTC by nsjcorps

I made only the modal content scrollable while the buttons and the title remain fixed.

@pushkalkatara @vkartik97  PTAL

2020-01-15 11:47 UTC, krtkvrm requested changes
Hi @nsjcorps 
Can you please post the screenshot in which the changes are reflected

2020-01-15 11:48 UTC, nsjcorps commented
How do I open the modal @vkartik97

2020-01-15 12:54 UTC, nsjcorps commented
![Screenshot (129)](https://user-images.githubusercontent.com/35180217/72435516-89886800-379e-11ea-8615-c20ee8671f29.png)

- Screenshot of fix

2020-01-15 12:55 UTC, nsjcorps commented
You can judge by the position of the scroll bar

2020-01-15 18:33 UTC, Sanji515 commented
Hey @nsjcorps there's one more modal for editing the phase details, which is not using the `utility/modal`. Can you please check this?

2020-01-15 18:35 UTC, nsjcorps commented
@Sanji515 no problem. Can you take a look at the other pr on code solitting

2020-01-15 19:56 UTC, nsjcorps commented
![Screenshot 1_15_2020 8_51_36 PM](https://user-images.githubcontent.com/35180217/72466544-662ede80-37d9-11ea-8376-e383f9c7acb2.png)

Please take a look @vkartik97 @Sanji515

2020-01-15 20:22 UTC, Sanji515 approved these changes
Thanks for the fix @nsjcorps , LGTM! This can be merged :tada:

2020-01-15 20:24 UTC, nsjcorps commented
Thanks.

2020-01-15 20:24 UTC, nsjcorps commented
Did you see the other PR? @Sanji515

2020-01-15 20:25 UTC, Sanji515 commented
> Did you see the other PR? @Sanji515

You mean [this](https://github.com/Cloud-CV/EvalAI-ngx/pull/274) right? Not yet, looking to it now.

2020-01-15 20:26 UTC, nsjcorps commented
Yes. That is correct

2020-01-17 08:09 UTC, lunayach commented on src/app/components/utility/modal/modal.component.html
> +        <ul style="margin-right: 20px;" class="inline-list pointer">
Please move this style to `.scss` file.

2020-01-17 08:25 UTC, nsjcorps commented on src/app/components/utility/modal/modal.component.html
> +        <ul style="margin-right: 20px;" class="inline-list pointer">
@lunayach I have updated the code.

2020-01-17 08:26 UTC, nsjcorps commented on src/app/components/utility/modal/modal.component.html
> +        <ul style="margin-right: 20px;" class="inline-list pointer">
@Sanji515 I submitted my task btw :)

2020-01-17 08:31 UTC, lunayach commented on src/app/components/utility/modal/modal.component.html
> +        <ul style="margin-right: 20px;" class="inline-list pointer">
Thanks, @nsjcorps.

2020-01-17 08:31 UTC, lunayach approved these changes

2020-01-17 09:36 UTC, merged