Update signup.html GCI
Cloud-CV/EvalAI-ngx pull request #280
Opened 2020-01-22 06:54 UTC by amanex007

* has been given to denote that the field is mandatory ti enter just like other fields like confirm password etc, corrected as per @vkartik97

2020-01-22 08:28 UTC, krtkvrm requested changes
Can you please fix the build

2020-01-22 08:37 UTC, amanex007 commented
> Can you please fix the build

The build problem was due to a small mistake, other than that i have edited the code as asked, but i have left the Asterix , to denote that the field is mandatory just like the confirm password field

2020-01-22 19:03 UTC, krtkvrm approved these changes

2020-01-23 15:52 UTC, Shekharrajak approved these changes

2020-01-23 17:05 UTC, Sanji515 approved these changes

2020-01-23 17:13 UTC, merged