Rebase feature added to contribution guideline
Cloud-CV/EvalAI-ngx pull request #294
Opened 2020-02-19 08:18 UTC by Kajol-Kumari

Feature Added:
All the commits related to a single issue can now be squashed into a single one making the PR more clean.The instruction for doing so is added in the contribution guideline.

For more detail regarding the feature, visit https://github.com/Cloud-CV/EvalAI/issues/2658

2020-02-19 17:12 UTC, Suryansh5545 requested changes

2020-02-19 17:12 UTC, Suryansh5545 commented on .github/CONTRIBUTING.md
> +***Congratulations, you have successfully contributed to Project EvalAI-ngx!***
Ngx is only a temporary name until the frontend is merged with backend so . We should let it stay as Evalai

2020-05-15 07:29 UTC, RishabhJain2018 approved these changes

2020-05-16 15:10 UTC, RishabhJain2018 commented
@Kajol-Kumari The build is failing on master branch here: https://travis-ci.org/github/Cloud-CV/EvalAI-ngx/builds/687325544#L894
cc: @Sanji515 @lunayach @Shekharrajak

2020-05-18 05:48 UTC, merged