Header component added
Cloud-CV/EvalAI-ngx pull request #33
Opened 2018-03-01 05:46 UTC by anweshknayak

Fixes #23

2018-03-01 05:47 UTC, anweshknayak commented
@aka-jain @spyshiv please review

2018-03-01 06:14 UTC, aka-jain commented
Fix travis check @anweshknayak

2018-03-01 06:14 UTC, aka-jain commented on src/app/components/header/header.component.html
> +      <a>Challenges</a>
Please use list elements here (`<li><a>Challenge</a></li>`)

2018-03-01 06:15 UTC, aka-jain commented on src/app/components/header/header.component.html
> +
New line.

2018-03-01 06:15 UTC, aka-jain commented on src/app/components/header/header.component.scss
> +* {box-sizing: border-box;}
These styles are already present in base.scss. Please check.

2018-03-01 06:15 UTC, aka-jain commented on src/app/components/header/header.component.scss
> +.header a {
Use proper scss syntax like
```
.header{
a{}
}
```

2018-03-01 06:16 UTC, aka-jain commented on src/app/components/header/header.component.scss
> +  background-color: #f1f1f1;
Use variables for color codes.

2018-03-01 06:16 UTC, aka-jain commented on src/app/components/header/header.component.scss
> +}
New Line.

2018-03-01 06:18 UTC, aka-jain commented
@anweshknayak please attach the screenshot of your final result.

2018-03-01 08:27 UTC, anweshknayak commented
@aka-jain changing to <li> </li>  made the UI behave weirdly. And also using the mixin for box-shadow made it look weird. So I have left those changes as of now. Rest done as you said. Also some minor changes in `tsconfig.app.json` to incorporate use of `require` keyword 
![screenshot from 2018-03-01 13-25-24](https://user-images.githubusercontent.com/8139783/36834248-4c8c5eaa-1d58-11e8-8142-0068d508a6cd.png)

2018-03-01 08:41 UTC, anweshknayak commented
I don't get why travis build is failing

2018-03-01 10:20 UTC, harshit98 commented
@anweshknayak Since you're using `app-header` inside `home.component.html`, try to import `HeaderComponent` in `home.component.spec.ts` as well. That might pass travis.

2018-03-01 10:21 UTC, spyshiv commented
@anweshknayak Check the travis log. 
These commands are failing
`ng test --watch=false` and `ng build --prod`
Please fix that. Let me know in case of any issue

2018-03-01 11:23 UTC, xamfy commented
also make logo public for ```ng build --prod to pass```

2018-03-01 15:14 UTC, anweshknayak commented
>ng build --env=prod
this worked but didn't show anything wrong in the log. @spyshiv @xamfy @harshit98

2018-03-01 15:40 UTC, xamfy commented
@anweshknayak  see https://stackoverflow.com/questions/43141576/property-x-is-private-and-only-accessible-within-class-xyzcomponent

2018-03-01 15:48 UTC, xamfy commented
pulled your changes and it shows the error while executing ```ng build --prod``` on my pc

2018-03-01 16:30 UTC, xamfy commented
for ```ng test --watch=false``` to pass
add headercompent in declarations in both app.component.spec.ts and home.component.spec.ts

2018-03-01 16:42 UTC, xamfy commented
@anweshknayak refer https://stackoverflow.com/questions/44504468/angular-2-karma-test-component-name-is-not-a-known-element

2018-03-01 17:23 UTC, xamfy commented
add headercomponent that you've imported in home.component.spec.ts in declarations, similar to app.component.spec.ts, test it on your machine first

2018-03-01 17:48 UTC, anweshknayak commented
thanks a lot @xamfy

2018-03-08 11:03 UTC, aka-jain requested changes

2018-03-08 11:03 UTC, aka-jain commented on src/app/components/header/header.component.scss
> +@import 'base.scss';
No need to add base.scss @anweshknayak . Base scss has already been applied to the whole app.

2018-03-08 11:03 UTC, aka-jain commented on src/app/components/header/header.component.scss
> +* {box-sizing: border-box;}
Remove this *

2018-03-08 13:45 UTC, anweshknayak commented on src/app/components/header/header.component.scss
> +@import 'base.scss';
@aka-jain instead `@import 'variables.scss';` otherwise webpack throws error ?

2018-03-08 13:47 UTC, anweshknayak commented on src/app/components/header/header.component.scss
> +* {box-sizing: border-box;}
remove the whole `* {box-sizing: border-box;}` ?
or just * ? Removing just * will give an error no ?

2018-03-08 22:03 UTC, spyshiv commented on src/app/components/header/header.component.scss
> +* {box-sizing: border-box;}
@anweshknayak  whole `* {..}`.

2018-03-09 04:38 UTC, anweshknayak commented
@aka-jain @spyshiv done the changes as requested.

2018-03-09 04:46 UTC, anweshknayak commented
tests for chromedriver is failing. @xamfy is it related to #43 ?

2018-03-09 04:49 UTC, spyshiv commented
@anweshknayak let me see PR #43 till then ignore Travis error

2018-03-09 18:12 UTC, anweshknayak commented
@spyshiv tests are passing.Please check

2018-04-28 08:56 UTC, aka-jain commented
Implementation is not correct. Closing this PR as will cover it again. cc @deshraj

2018-04-28 08:56 UTC, closed without merging