Privacy policy page with smart scroll
Cloud-CV/EvalAI-ngx pull request #64
Opened 2018-05-08 15:58 UTC by live-wire

Privacy policy page available at path `/privacy-policy`
Supposed to close #50 
- Implemented a smart scroll navigation for this page
(I removed this scroll-nav functionality for mobile view as it looks too cluttered).

> The header will look better once #61 is merged

2018-05-08 18:08 UTC, aka-jain requested changes
What is smart scrolling @live-wire can you please explain here.

2018-05-08 18:08 UTC, aka-jain commented on src/app/privacy-policy/privacy-policy.component.scss
> +@import '../../styles/base.scss';
I think you don't have to import `base` and `grid` again and again  @live-wire

2018-05-08 18:08 UTC, aka-jain commented on src/app/privacy-policy/privacy-policy.component.ts
> +    const idText = 'privacy-';
for const use variable in capital letters eg. const IDTEXT @live-wire

2018-05-09 17:37 UTC, live-wire commented
*Smart scrolling* is just a term I came up with 🙈 
There is a navigation-indicator on the left which shows what section we're currently at in the privacy policy. It has the following features:
- Highlight the nav element for the selected section (red).
- Links to the corresponding section and scrolls it into view on click.
- Automatically updates the selected section when the page is manually scrolled.
- Disappears in mobile-view (It was too cluttered)

Elements in the *nav* are decided by checking for class: `privacy-nav`
Elements in the corrsponding titles are decided by checking for class: `privacy-section-title`

2018-05-09 17:42 UTC, live-wire commented
Hey @aka-jain, I updated this PR with the suggested changes. Please have a look. 🎈

2018-05-20 10:06 UTC, aka-jain requested changes

2018-05-20 10:06 UTC, aka-jain commented on src/app/privacy-policy/privacy-policy.component.html
> +<div class="privacy-nav-container col-lg-2 col-md-3 col-sm-5 col-xs-5">
Wrap col under row @live-wire

2018-05-20 10:06 UTC, aka-jain commented on src/styles/variables.scss
> +$screen-md: 1130px;
New line @live-wire

2018-05-21 03:35 UTC, live-wire commented
Made the suggested changes @aka-jain 🏃

2018-06-04 21:43 UTC, live-wire commented
![jun-4-2018-11_26-pm](https://user-images.githubusercontent.com/6399428/40942603-046c88ce-684f-11e8-9e69-d062d5223275.gif)
☝️ This is how the `/privacy-policy` page looks like

Please have a look @spyshiv @aka-jain @RishabhJain2018 🍬 

cc: @shivaniprakash95

2018-06-15 13:59 UTC, RishabhJain2018 commented
I have tested it & it works fine.

2018-06-21 11:57 UTC, RishabhJain2018 commented
@live-wire Can you please check why travis build fails?

2018-06-21 20:57 UTC, RishabhJain2018 commented
@live-wire Please resolve the merge conflicts.

2018-06-25 07:45 UTC, RishabhJain2018 commented
@live-wire More merge conflicts 😄

2018-06-25 14:56 UTC, live-wire commented
@RishabhJain2018 resolved them conflicts :D

2018-06-26 08:16 UTC, RishabhJain2018 approved these changes
LGTM :)
@aka-jain @spyshiv Can we merge this PR ?

2018-06-29 06:32 UTC, aka-jain approved these changes

2018-06-29 06:32 UTC, merged