docker instructions added
Cloud-CV/EvalAI-ngx pull request #7
Opened 2018-02-04 10:52 UTC by anweshknayak

fix #5 @deshraj @RishabhJain2018 please review

2018-02-07 18:59 UTC, aka-jain commented on README.md
> +git clone https://github.com/Cloud-CV/EvalAI-ngx.git && cd EvalAI-ngx
@anweshknayak please refer steps from here https://github.com/Cloud-CV/EvalAI/blob/master/README.md#using-docker
Write down in this way.

2018-02-08 10:22 UTC, anweshknayak commented
@aka-jain done. Also should I add this
 `cp settings/dev.sample.py settings/dev.py` ? I have skipped this part for now

2018-02-11 18:09 UTC, deshraj requested changes

2018-02-11 18:09 UTC, deshraj commented on README.md
> +### Using Docker
Change it to `## Setup using Docker`

2018-02-12 09:19 UTC, anweshknayak commented
@deshraj updated

2018-02-14 18:16 UTC, deshraj approved these changes

2018-02-14 18:17 UTC, merged