Contact page
Cloud-CV/EvalAI-ngx pull request #71
Opened 2018-05-23 18:55 UTC by live-wire

This is supposed to close #59 
The page is accessible at path `/contact`

This PR is dependent on the form-component PR #70 

> Header will look better once #61 is merged.

Please have a look @RishabhJain2018 @shivaniprakash95 @aka-jain @spyshiv 🍔

2018-06-02 13:41 UTC, live-wire commented
![contact](https://user-images.githubusercontent.com/6399428/40874841-0f3329b0-6675-11e8-989b-d0d5b3897699.gif)
This is how the page will look ☝️ 
> This also contains form validation logic (added to Global Service).
> This PR is dependent on #70 . Please merge that before this. 

Please have a look @aka-jain 🌯 
cc: @RishabhJain2018 @spyshiv

2018-06-14 01:58 UTC, live-wire commented
Added the API request to this. Please merge #70 before this.
This also contains common code for the API service which will be required by other pages as well. Please review it soon 🍕 


cc: @aka-jain @spyshiv @RishabhJain2018 @shivaniprakash95 @deshraj

2018-06-15 13:29 UTC, RishabhJain2018 requested changes
Apart from the links in header, it works perfectly!

2018-06-15 13:29 UTC, RishabhJain2018 commented on src/app/contact/contact.component.html
> +              <td><img src="assets/images/fb.png" /></td>
Please add links to cloudcv fb [page](https://www.facebook.com/mlcloudcv/)

2018-06-15 13:29 UTC, RishabhJain2018 commented on src/app/contact/contact.component.html
> +              <td><img src="assets/images/git.png" /></td>
Same as above.

2018-06-15 13:29 UTC, RishabhJain2018 commented on src/app/contact/contact.component.html
> +              <td><img src="assets/images/twitter.png" /></td>
same as above.

2018-06-15 22:50 UTC, live-wire commented
Thanks for the links @RishabhJain2018 😄 I made the changes you suggested. 
Please have a look 🔢

2018-06-21 12:06 UTC, RishabhJain2018 commented
@live-wire Can you please check why the travis build is failing.

2018-06-21 12:18 UTC, RishabhJain2018 commented
@live-wire I think we should also display the toast notification to the user saying some like `we have received your query and will reply soon`.
Please refer to the current version of EvalAI.

2018-06-21 12:57 UTC, live-wire commented
@RishabhJain2018 I added a `TODO` for that in this PR.

Custom Toasts are a part of #77 and the toast you mentioned is added there 😄

2018-06-26 08:33 UTC, RishabhJain2018 approved these changes
LGTM :)
@aka-jain @spyshiv Can we merge this PR ?

2018-07-06 10:56 UTC, RishabhJain2018 commented
@live-wire More conflicts :D

2018-07-06 15:21 UTC, live-wire commented
I'll resolve these right after #66 is merged 💃

2018-07-08 12:53 UTC, RishabhJain2018 commented
@live-wire Please resolve the merge conflicts here.

2018-07-08 12:54 UTC, live-wire commented
On it!

2019-03-03 21:55 UTC, RishabhJain2018 commented
Closing this since it is already merged.

2019-03-03 21:55 UTC, closed without merging