Auth page
Cloud-CV/EvalAI-ngx pull request #74
Opened 2018-05-28 14:58 UTC by live-wire

This is supposed to close #51 
Contains changes for login and signup page at path `auth/login` and `auth/signup`

Depends on #70 

Please have a look @aka-jain @spyshiv @RishabhJain2018 @shivaniprakash95

2018-05-30 09:49 UTC, aka-jain requested changes

2018-05-30 09:49 UTC, aka-jain commented on src/app/auth/auth.component.html
> +        <a [class.auth-selected]="localRouter.url=='/auth/login'"  (click)="navigateTo('/auth/login')">LOGIN</a>
Adding click to anchor tag is not a good Practice instead use routerLink for the navigation @live-wire

2018-05-30 09:49 UTC, aka-jain commented on src/app/auth/auth.component.html
> +        <a [class.auth-selected]="localRouter.url=='/auth/login'"  (click)="navigateTo('/auth/login')">LOGIN</a>
Use like this `<a [routerLink]="['URL']" routerLinkActive="auth-selected">` @live-wire

2018-05-30 09:49 UTC, aka-jain commented on src/app/auth/auth.component.html
> +        <table>
Don't use table, instead use `ul li` elements they are easily customisable. @live-wire

2018-05-30 09:49 UTC, aka-jain commented on src/app/input/input.component.scss
> +  .input-field.theme-dark{
You can write this as 
`.input-field{
     &.theme-dark{
     }
}`
 also @live-wire

2018-05-30 09:49 UTC, aka-jain commented on src/app/signup/signup.component.scss
> +	}}}
Indentations @live-wire

2018-05-30 09:52 UTC, aka-jain commented
Attach screenshot of your final result @live-wire

2018-06-02 12:20 UTC, live-wire commented
![auth](https://user-images.githubusercontent.com/6399428/40852586-2dd1a52c-65cb-11e8-90bd-700c5cdb95a3.gif)
This is how the page looks like ☝️ 
> This PR is dependent on #70 (Please merge that before merging this)



I made the changes that you suggested @aka-jain . Please have a look 🥘 

cc: @RishabhJain2018 @spyshiv

2018-06-15 13:43 UTC, RishabhJain2018 commented
I have tested it. It works fine as of now but it is a static page, I think we should integrate it backend.

2018-06-21 12:15 UTC, RishabhJain2018 commented
@live-wire Please resolve the merge conflicts.

2018-06-25 07:44 UTC, RishabhJain2018 commented
@live-wire If this is completed then please move it to under review section, so that we can check it.

2018-06-26 08:30 UTC, RishabhJain2018 commented
@live-wire I tried to test it on my local, but it is giving me some error
While logging in the error screenshot is
<img width="1440" alt="screen shot 2018-06-26 at 1 51 09 pm" src="https://user-images.githubusercontent.com/12206047/41899080-2948d6b0-7949-11e8-97fd-90024d476e94.png">
Also, while signing up the error screenshot is:
<img width="1440" alt="screen shot 2018-06-26 at 1 52 18 pm" src="https://user-images.githubusercontent.com/12206047/41899111-3d1a0560-7949-11e8-9667-cc7b7eec1ade.png">

2018-06-28 01:17 UTC, live-wire commented
@RishabhJain2018 I moved the form error handling logic to global service! 
I think there is no use displaying all server-error responses to the user. 
I decided if the error is internal like above, I'd display this in the toast: 
`something went wrong <code>`

Please try now. 
I am still facing an issue while signing up. Signing up seems to create an account successfully but the API response is a 500 with the following error:
```
TypeError at /api/auth/registration/
is_safe_url() got an unexpected keyword argument 'allowed_hosts'

Request Method: POST
Request URL: http://localhost:8000/api/auth/registration/
Django Version: 1.10.2
Python Executable: /usr/local/bin/python
Python Version: 2.7.14
Python Path: ['/code', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/code/apps', '/usr/local/lib/python2.7/site-packages/odf', '/usr/local/lib/python2.7/site-packages/odf', '/usr/local/lib/python2.7/site-packages/odf', '/usr/local/lib/python2.7/site-packages/odf', '/usr/local/lib/python2.7/site-packages/odf', '/usr/local/lib/python2.7/site-packages/odf', '/usr/local/lib/python2.7/site-packages/odf']
Server time: Wed, 27 Jun 2018 23:18:59 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'accounts',
 'analytics',
 'base',
 'challenges',
 'hosts',
 'jobs',
 'participants',
 'web',
 'allauth',
 'allauth.account',
 'corsheaders',
 'django_ses',
 'import_export',
 'rest_auth',
 'rest_auth.registration',
 'rest_framework.authtoken',
 'rest_framework',
 'rest_framework_docs',
 'rest_framework_expiring_authtoken',
 'django_spaghetti',
 'autofixture',
 'debug_toolbar',
 'django_extensions',
 'silk']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'silk.middleware.SilkyMiddleware']


Traceback:  

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  76.             return view(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/local/lib/python2.7/site-packages/rest_auth/registration/views.py" in dispatch
  39.         return super(RegisterView, self).dispatch(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  477.             response = self.handle_exception(exc)

File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py" in handle_exception
  437.             self.raise_uncaught_exception(exc)

File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  474.             response = handler(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/rest_framework/generics.py" in post
  191.         return self.create(request, *args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/rest_auth/registration/views.py" in create
  58.         user = self.perform_create(serializer)

File "/usr/local/lib/python2.7/site-packages/rest_auth/registration/views.py" in perform_create
  74.                         None)

File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py" in complete_signup
  183.                          signal_kwargs=signal_kwargs)

File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py" in perform_login
  152.             get_login_redirect_url(request, redirect_url))

File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py" in get_login_redirect_url
  50.             redirect_field_name=redirect_field_name) or

File "/usr/local/lib/python2.7/site-packages/allauth/account/utils.py" in get_next_redirect_url
  36.     if not get_adapter(request).is_safe_url(redirect_to):

File "/usr/local/lib/python2.7/site-packages/allauth/account/adapter.py" in is_safe_url
  410.         return is_safe_url(url, allowed_hosts=None)

Exception Type: TypeError at /api/auth/registration/
Exception Value: is_safe_url() got an unexpected keyword argument 'allowed_hosts'
Request information:
USER: dbadbadba

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:
CONTENT_LENGTH = '105'
CONTENT_TYPE = 'application/json'
CSRF_COOKIE = u'SG2gyXyeOkVk6aRtOfSveBSj2963eEeuN6zcfGmX51FSfFCCIR978gP1uTFgIYrs'
CSRF_COOKIE_USED = True
DEBUG = 'True'
DJANGO_SERVER = 'django'
DJANGO_SETTINGS_MODULE = 'settings'
GATEWAY_INTERFACE = 'CGI/1.1'
GPG_KEY = 'C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF'
HOME = '/root'
HOSTNAME = 'django'
HTTP_ACCEPT = 'application/json, text/plain, */*'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'en-US,en-NL;q=0.9,en;q=0.8'
HTTP_CACHE_CONTROL = 'no-cache'
HTTP_CONNECTION = 'keep-alive'
HTTP_HOST = 'localhost:8000'
HTTP_ORIGIN = 'http://localhost:4200'
HTTP_PRAGMA = 'no-cache'
HTTP_REFERER = 'http://localhost:4200/auth/signup'
HTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36'
LANG = 'C.UTF-8'
OLDPWD = '/code'
PATH = '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PATH_INFO = u'/api/auth/registration/'
POSTGRES_HOST = 'db'
POSTGRES_NAME = 'postgres'
POSTGRES_PASSWORD = 'postgres'
POSTGRES_PORT = '5432'
POSTGRES_USER = 'postgres'
PWD = '/code'
PYTHONUNBUFFERED = '1'
PYTHON_PIP_VERSION = '9.0.1'
PYTHON_VERSION = '2.7.14'
QUERY_STRING = ''
RABBITMQ_HOST = 'rabbitmq'
REMOTE_ADDR = '172.20.0.1'
REMOTE_HOST = ''
REQUEST_METHOD = 'POST'
RUN_MAIN = 'true'
SCRIPT_NAME = u''
SERVER_NAME = 'django'
SERVER_PORT = '8000'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SOFTWARE = 'WSGIServer/0.1 Python/2.7.14'
SHLVL = '0'
TZ = 'UTC'
wsgi.errors = <open file '<stderr>', mode 'w' at 0x7f45967311e0>
wsgi.file_wrapper = ''
wsgi.input = <socket._fileobject object at 0x7f4582b05ad0>
wsgi.multiprocess = False
wsgi.multithread = True
wsgi.run_once = False
wsgi.url_scheme = 'http'
wsgi.version = 

Settings:
Using settings module settings
ABSOLUTE_URL_OVERRIDES = {}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/api/auth/email-confirmed/'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/api/auth/email-confirmed/'
ACCOUNT_EMAIL_REQUIRED = True
ADMINS = []
ADMI [...]

2018-07-03 04:03 UTC, RishabhJain2018 commented
@live-wire Please resolve the merge conflicts.

2018-07-06 11:05 UTC, RishabhJain2018 commented
@live-wire I am able to signup but not login
Here is the screenshot of the error
<img width="1440" alt="screen shot 2018-07-06 at 4 33 21 pm" src="https://user-images.githubusercontent.com/12206047/42375806-65e59cf4-813a-11e8-9248-6044f3759244.png">

Moreover, please don't display error code in the notification. Also, notification can be a little more smoother.

2018-07-06 15:12 UTC, live-wire commented
I fixed this login issue in one of the upcoming PRs 🙈 
Will fix it here as well. 
It is so difficult to maintain so many open PRs 😢

2018-07-06 15:22 UTC, live-wire commented
I'll update this PR right after #66  and #71  are merged 💃

2019-03-03 21:54 UTC, RishabhJain2018 commented
closing this since it is already merged.

2019-03-03 21:54 UTC, closed without merging