Custom Toasts
Cloud-CV/EvalAI-ngx pull request #77
Opened 2018-06-20 12:19 UTC by live-wire

This is w.r.t the issue #76 

> This PR is extended upon the contact page PR #71  (Please merge that before this)

This contains three kinds of toasts as per the design spec:
- error
- success 
- info

2018-06-20 12:58 UTC, live-wire commented
![jun-20-2018-2_56-pm](https://user-images.githubusercontent.com/6399428/41659707-4ea8027c-749a-11e8-95bf-91f4bb6bd73c.gif)
This is how the `success` toast looks like 🐝

2018-06-20 13:59 UTC, shivaniprakash95 commented
Looks Good to me!

2018-06-26 08:36 UTC, RishabhJain2018 requested changes

2018-06-26 08:36 UTC, RishabhJain2018 commented on src/app/app.component.html
> +<app-toast></app-toast>
Please add a new line here.

2018-06-26 08:36 UTC, RishabhJain2018 commented on src/app/contact/contact.component.html
> +      <br>
I think we should avoid using `<br>` instead use the `margin-bottom`.

2018-07-06 11:06 UTC, RishabhJain2018 commented
@live-wire Please update the PR.

2018-07-06 15:31 UTC, live-wire commented
Dependent on #71 
Will resolve these after #71  is merged 🕺

2019-03-03 21:55 UTC, RishabhJain2018 commented
Closing this since it is already merged.

2019-03-03 21:55 UTC, closed without merging