All challenges
Cloud-CV/EvalAI-ngx pull request #84
Opened 2018-07-01 03:38 UTC by live-wire

Supposed to close #60 
This is the complete PR for All Challenges.

As of now, in `My Challenges` displays only the challenges that are `hosted` by a team which the current user is a part of. Should it also display the challenges that the current user is `participating` in ? cc: @deshraj 

Please have a look @RishabhJain2018 @aka-jain @spyshiv 🍕

2018-07-01 14:51 UTC, RishabhJain2018 commented
@live-wire Please check why the travis build is failing. Moreover,I suggest you to now work in parallel 💻 in order to increase the coverage as current coverage is 59% 😞. We need to increase it to 90% at least 😃 . I am asking this for now as we haven't merged a lot of features for now so it will be easy to increase the coverage. Once the codebase increases then we won't be able to achieve it and also things might break without tests.

2018-07-02 05:51 UTC, live-wire commented
Sure @RishabhJain2018 I'll create an issue to track this and start improving the coverage soon.

2018-07-02 15:18 UTC, deshraj commented
Strongly agree with what @RishabhJain2018 said. @live-wire please add tests along with each feature otherwise there is no point in building the features.

2018-07-03 09:30 UTC, live-wire commented
@deshraj I agree. I'll add the tests soon. I am building everything as modular/functional as possible. I'll make sure I write good tests too 😄

2018-07-06 11:23 UTC, RishabhJain2018 commented
@live-wire Ohhh..I missed your first question. Regarding the `My Challenges` part we should have a section for both hosted and participated challenges by a user.

2018-07-06 11:24 UTC, RishabhJain2018 requested changes

2018-07-06 11:24 UTC, RishabhJain2018 commented on src/app/app.component.html
> +<app-toast></app-toast>
Please add a new line here!

2018-07-06 12:12 UTC, RishabhJain2018 commented
@live-wire please take of this:
<img width="1440" alt="screen shot 2018-07-06 at 5 08 29 pm" src="https://user-images.githubusercontent.com/12206047/42378165-eb4abdbc-8143-11e8-8c60-e07fe3a4c280.png">

2018-07-06 13:39 UTC, live-wire commented
@RishabhJain2018  That Authentication issue is because of fetching the stars which is supposed to change in the API :)

2019-03-03 21:52 UTC, RishabhJain2018 commented
Closing this since it is already merged.

2019-03-03 21:52 UTC, closed without merging